
all:
	g++ -o browserHistory browserHistory.cpp util.cpp
	g++ -o cipher cipher.cpp
	g++ -o codeverifier codeverifier.cpp
	g++ -o easierinput easierinput.cpp
	g++ -o gameOfLife gameOfLife.cpp util.cpp
	g++ -o moviept3 moviept3.cpp
	g++ -o necklace necklace.cpp
	g++ -o printerSimulation printerSimulation.cpp util.cpp
	g++ -o rpnCalculator rpnCalculator.cpp util.cpp
	g++ -o syntaxChecker syntaxChecker.cpp util.cpp
	g++ -o cardShuffler cardShuffler.cpp util.cpp
	g++ -o visitTeams visitTeams.cpp util.cpp
	g++ -o moviept4 moviept4.cpp util.cpp
	g++ -o bingo bingo.cpp util.cpp
	g++ -o wordCounter wordCounter.cpp util.cpp
	g++ -o carRegistrar carRegistrar.cpp util.cpp
	g++ -o frc frc.cpp util.cpp
	g++ -o sumDigits sumDigits.cpp util.cpp
