
all:
	g++ -g -o browserHistory browserHistory.cpp util.cpp
	g++ -g -o cipher cipher.cpp
	g++ -g -o codeverifier codeverifier.cpp
	g++ -g -o easierinput easierinput.cpp
	g++ -g -o gameOfLife gameOfLife.cpp util.cpp
	g++ -g -o moviept3 moviept3.cpp
	g++ -g -o necklace necklace.cpp
	g++ -g -o printerSimulation printerSimulation.cpp util.cpp
	g++ -g -o rpnCalculator rpnCalculator.cpp util.cpp
	g++ -g -o syntaxChecker syntaxChecker.cpp util.cpp
	g++ -g -o cardShuffler cardShuffler.cpp util.cpp
	g++ -g -o visitTeams visitTeams.cpp util.cpp
	g++ -g -o moviept4 moviept4.cpp util.cpp
	g++ -g -o bingo bingo.cpp util.cpp
	g++ -g -o wordCounter wordCounter.cpp util.cpp
	g++ -g -o carRegistrar carRegistrar.cpp util.cpp
	g++ -g -o frc frc.cpp util.cpp
	g++ -g -o sumDigits sumDigits.cpp util.cpp
	g++ -g -o removeA removeA.cpp util.cpp
	g++ -g -o validDNA validDNA.cpp util.cpp
	g++ -g -o isSubSeqence isSubSequence.cpp util.cpp
	g++ -g -o printAllBinPermutations printAllBinPermutations.cpp util.cpp
	g++ -g -o pascalTriangle pascalTriangle.cpp util.cpp
	g++ -g -o phoneWords phoneWords.cpp util.cpp
	g++ -g -o diceSum diceSum.cpp util.cpp
	g++ -g -o airFreight airFreight.cpp util.cpp
	g++ -g -o cellPhoneTowers cellPhoneTowers.cpp util.cpp
	g++ -g -o sudokuSolver sudokuSolver.cpp util.cpp
	g++ -g -o printStats printStats.cpp util.cpp
	g++ -g -o stocks stocks.cpp util.cpp
	g++ -g -o stupendouslyLongDivision stupendouslyLongDivision.cpp util.cpp
clean:
	@echo "Cleaning up..."
	find . -type f ! -name '*.*' ! -name 'Makefile' -exec rm -f {} +
	@echo "Cleanup complete."
