
all:
	g++ -g -o browserHistory browserHistory.cpp util.cpp
	g++ -g -o cipher cipher.cpp
	g++ -g -o codeverifier codeverifier.cpp
	g++ -g -o easierinput easierinput.cpp
	g++ -g -o gameOfLife gameOfLife.cpp util.cpp
	g++ -g -o moviept3 moviept3.cpp
	g++ -g -o necklace necklace.cpp
	g++ -g -o printerSimulation printerSimulation.cpp util.cpp
	g++ -g -o rpnCalculator rpnCalculator.cpp util.cpp
	g++ -g -o syntaxChecker syntaxChecker.cpp util.cpp
	g++ -g -o cardShuffler cardShuffler.cpp util.cpp
	g++ -g -o visitTeams visitTeams.cpp util.cpp
	g++ -g -o moviept4 moviept4.cpp util.cpp
	g++ -g -o bingo bingo.cpp util.cpp
	g++ -g -o wordCounter wordCounter.cpp util.cpp
	g++ -g -o carRegistrar carRegistrar.cpp util.cpp
	g++ -g -o frc frc.cpp util.cpp
	g++ -g -o sumDigits sumDigits.cpp util.cpp
	g++ -g -o removeA removeA.cpp util.cpp
	g++ -g -o validDNA validDNA.cpp util.cpp
	g++ -g -o isSubSeqence isSubSequence.cpp util.cpp
	g++ -g -o printAllBinPermutations printAllBinPermutations.cpp util.cpp
	g++ -g -o pascalTriangle pascalTriangle.cpp util.cpp
	g++ -g -o phoneWords phoneWords.cpp util.cpp
